#!/usr/bin/env python3
"""Render a small, dependency-free HTML coverage index from LCOV files."""

from __future__ import annotations

import argparse
import html
from pathlib import Path


def parse_lcov(path: Path) -> tuple[int, int]:
    found = hit = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("DA:"):
            _, value, *_ = line[3:].split(",")
            found += 1
            hit += int(value) > 0
    return hit, found


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--report", action="append", required=True)
    args = parser.parse_args()
    rows = []
    for item in args.report:
        name, report = item.split("=", 1)
        hit, found = parse_lcov(Path(report))
        percent = 100.0 if found == 0 else hit * 100.0 / found
        rows.append(f"<tr><td>{html.escape(name)}</td><td>{hit}/{found}</td><td>{percent:.2f}%</td></tr>")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "<!doctype html><meta charset=utf-8><title>Brickbed coverage</title>"
        "<style>body{font:16px system-ui;margin:3rem;max-width:56rem}table{border-collapse:collapse}td,th{padding:.5rem 1rem;border:1px solid #bbb;text-align:left}</style>"
        "<h1>Brickbed coverage</h1><p>Generated by <code>scripts/coverage.sh</code>.</p>"
        "<table><thead><tr><th>Suite</th><th>Covered lines</th><th>Coverage</th></tr></thead><tbody>"
        + "".join(rows)
        + "</tbody></table>",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
